name: scraper
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 4"
jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scrape
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL}}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          npm install
          npm run scrape
