name: scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 4"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Scrape
        run: 'curl --request POST "${{ secrets.API_URL}}" --header "Authorization: Bearer ${{ secrets.API_URL}}"'
