name: scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 4"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - name: Scrape
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL}}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          pnpm install
          pnpm run scrape
